package soft.ce.telegram.dto;

public enum BotState {
    PICK_LANGUAGE,
    START,

    AUTHORIZATION,
    USER_INFO,
    USERNAME,
    RECORD_USERNAME,
    GROUP_NAME,
    RECORD_GROUP_NAME,

    APPLICATION,
    APPLICATION_HEALTH,
    APPLICATION_PASS_EXAM,
    APPLICATION_OTHER,
    CONFIRMATION_FILE,

    FINISH
}
